In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import tensorflow as tf
import keras
import librosa
from librosa import display
%matplotlib inline

In [5]:
from keras.models import load_model

model = load_model("/content/drive/MyDrive/UGP23/dataset/Yoga_82_modified/weights_yoga82.best_ann.hdf5")

In [6]:
test = pd.read_csv("/content/drive/MyDrive/UGP23/dataset/Yoga_82_modified/test_keypoints_yoga82.csv")

In [7]:
test.labels.value_counts()

6    69
4    60
8    47
5    40
3    40
7    34
2    31
0    28
1    27
Name: labels, dtype: int64

In [8]:
x_test = test.drop(['file_name', 'labels'], axis=1)
y_test = test.labels

In [9]:
y_pred = model.predict(x_test)

12/12 [==============================] - 0s 4ms/step


In [10]:
y_pred = np.argmax(y_pred, axis=1)
y_pred

array([4, 0, 6, 0, 5, 4, 3, 6, 6, 3, 5, 6, 1, 3, 8, 0, 3, 3, 5, 6, 7, 6,
       2, 0, 6, 6, 4, 6, 3, 6, 5, 6, 6, 8, 4, 4, 3, 0, 6, 4, 6, 6, 4, 6,
       4, 0, 4, 2, 4, 2, 8, 2, 8, 6, 0, 1, 7, 8, 6, 7, 7, 8, 4, 4, 6, 3,
       5, 3, 0, 4, 7, 2, 6, 4, 3, 3, 3, 8, 2, 7, 8, 7, 2, 1, 8, 3, 7, 7,
       5, 6, 7, 5, 8, 4, 1, 7, 6, 5, 0, 5, 4, 4, 5, 0, 0, 4, 0, 8, 1, 6,
       6, 4, 5, 6, 4, 1, 8, 6, 5, 8, 2, 3, 2, 3, 6, 6, 7, 6, 1, 4, 6, 6,
       7, 1, 8, 8, 4, 2, 6, 7, 5, 6, 0, 8, 2, 2, 3, 0, 5, 8, 4, 5, 5, 8,
       8, 4, 8, 8, 6, 0, 0, 1, 2, 7, 0, 7, 8, 5, 7, 6, 0, 7, 8, 6, 4, 4,
       5, 7, 2, 6, 8, 2, 4, 5, 8, 4, 6, 0, 5, 4, 7, 6, 4, 5, 6, 8, 8, 6,
       6, 6, 3, 7, 7, 4, 3, 6, 8, 2, 6, 4, 0, 6, 2, 6, 8, 8, 8, 7, 0, 4,
       0, 8, 6, 6, 1, 6, 5, 5, 1, 4, 4, 0, 6, 0, 5, 5, 5, 2, 3, 6, 2, 8,
       8, 2, 8, 1, 2, 6, 3, 3, 2, 7, 6, 4, 3, 7, 8, 1, 6, 3, 0, 8, 2, 5,
       1, 7, 3, 4, 8, 8, 8, 5, 7, 0, 7, 6, 6, 8, 3, 7, 2, 4, 4, 7, 8, 6,
       4, 8, 1, 6, 6, 5, 2, 1, 6, 6, 3, 6, 1, 1, 0,

In [11]:
y_test = np.array(y_test)
y_test

array([4, 0, 6, 0, 5, 4, 3, 4, 6, 3, 5, 6, 1, 3, 8, 0, 3, 3, 5, 6, 7, 6,
       2, 0, 6, 6, 4, 6, 3, 6, 5, 3, 6, 8, 4, 4, 3, 0, 6, 4, 6, 6, 4, 6,
       4, 0, 4, 2, 4, 2, 8, 2, 8, 6, 0, 3, 7, 7, 6, 2, 7, 8, 4, 4, 6, 3,
       5, 3, 1, 4, 7, 2, 6, 4, 3, 3, 3, 8, 2, 7, 8, 7, 2, 1, 8, 3, 7, 7,
       5, 6, 7, 5, 8, 4, 1, 7, 6, 5, 0, 5, 4, 4, 5, 0, 0, 4, 0, 8, 1, 6,
       6, 4, 6, 6, 4, 1, 8, 6, 5, 8, 2, 3, 2, 3, 4, 6, 7, 6, 1, 4, 6, 6,
       7, 1, 8, 8, 4, 2, 6, 7, 5, 6, 0, 8, 2, 2, 3, 0, 5, 8, 4, 5, 5, 8,
       8, 4, 8, 4, 6, 0, 0, 1, 2, 7, 0, 3, 8, 5, 7, 6, 0, 7, 8, 6, 4, 4,
       5, 7, 2, 6, 8, 2, 4, 5, 8, 4, 6, 0, 5, 4, 7, 6, 4, 5, 5, 8, 8, 6,
       6, 6, 3, 7, 7, 4, 3, 6, 8, 2, 6, 4, 0, 6, 2, 6, 8, 8, 8, 7, 0, 4,
       0, 8, 6, 6, 1, 6, 5, 5, 1, 4, 4, 4, 6, 0, 5, 5, 5, 2, 3, 6, 2, 8,
       8, 2, 8, 1, 2, 6, 3, 3, 2, 7, 6, 4, 3, 7, 8, 1, 8, 3, 0, 8, 2, 5,
       1, 6, 3, 4, 4, 8, 8, 5, 7, 0, 7, 6, 6, 8, 3, 7, 2, 4, 4, 7, 8, 6,
       4, 8, 1, 6, 6, 5, 2, 1, 6, 6, 3, 6, 1, 1, 0,

In [12]:
print(y_pred.shape)
print(y_test.shape)

(376,)
(376,)


In [13]:
wrong_indices = np.nonzero(y_pred != y_test)
wrong_indices

(array([  7,  31,  55,  57,  59,  68, 112, 124, 157, 165, 194, 231, 258,
        265, 268, 362]),)

In [14]:
wrong_indices[0].size

16

In [15]:
test.iloc[wrong_indices]['file_name'].values

array(['1_100.jpg', '0_495.jpg', '129.jpg', '151.jpg', '0_38.jpg',
       '1_344.jpg', '1_120.jpg', '2_1.jpg', '1_30.jpg', '423.jpg',
       '0_205.jpg', '1_0_486.jpg', '242.jpg', '3_238.jpg', '1_335.jpg',
       '94.jpg'], dtype=object)

In [16]:
wrong_indices = np.nonzero(y_pred != y_test)
wrong_predicted_df = test.iloc[wrong_indices].copy()
wrong_predicted_df['y_test'] = y_test[wrong_indices]
wrong_predicted_df['y_pred'] = y_pred[wrong_indices]
wrong_predicted = wrong_predicted_df[['file_name', 'y_test', 'y_pred']]
wrong_predicted

file_name  y_test  y_pred
7      1_100.jpg       4       6
31     0_495.jpg       3       6
55       129.jpg       3       1
57       151.jpg       7       8
59      0_38.jpg       2       7
68     1_344.jpg       1       0
112    1_120.jpg       6       5
124      2_1.jpg       4       6
157     1_30.jpg       4       8
165      423.jpg       3       7
194    0_205.jpg       5       6
231  1_0_486.jpg       4       0
258      242.jpg       8       6
265    3_238.jpg       6       7
268    1_335.jpg       4       8
362       94.jpg       8       5

In [17]:
wrong_predicted.to_csv("/content/drive/MyDrive/UGP23/dataset/Yoga_82_modified/wrong_predicted.csv", index=False)

In [23]:
def y_to_pose (y):
    if(y==0): pose = 'Plank_Pose_or_Kumbhakasana_'    
    if(y==1): pose = 'Warrior_I_Pose_or_Virabhadrasana_I_'  
    if(y==2): pose = 'Standing_big_toe_hold_pose_or_Utthita_Padangusthasana'     
    if(y==3): pose = 'Warrior_II_Pose_or_Virabhadrasana_II_'     
    if(y==4): pose = 'Cat_Cow_Pose_or_Marjaryasana_'
    if(y==5): pose = 'Child_Pose_or_Balasana_'  
    if(y==6): pose = 'Cobra_Pose_or_Bhujangasana_'     
    if(y==7): pose = 'Tree_Pose_or_Vrksasana_'     
    if(y==8): pose = 'Downward-Facing_Dog_pose_or_Adho_Mukha_Svanasana_'
    return pose

In [24]:
!pip install -q mediapipe

In [25]:
folder_path = "/content/drive/MyDrive/UGP23/dataset/Yoga_82_modified/yoga_82"

In [26]:
os.listdir(folder_path)

['Plank_Pose_or_Kumbhakasana_',
 'Warrior_I_Pose_or_Virabhadrasana_I_',
 'Standing_big_toe_hold_pose_or_Utthita_Padangusthasana',
 'Warrior_II_Pose_or_Virabhadrasana_II_',
 'Cat_Cow_Pose_or_Marjaryasana_',
 'Child_Pose_or_Balasana_',
 'Cobra_Pose_or_Bhujangasana_',
 'Tree_Pose_or_Vrksasana_',
 'Downward-Facing_Dog_pose_or_Adho_Mukha_Svanasana_']

In [28]:
import os
import matplotlib.pyplot as plt
import cv2
import mediapipe as mp

mp_pose = mp.solutions.pose
mp_drawing = mp.solutions.drawing_utils
pose = mp_pose.Pose(static_image_mode=True, min_detection_confidence=0.5, model_complexity=2)

for idx, row in wrong_predicted.iterrows():
    file_name = row['file_name']
    pose_name = str(y_to_pose(row['y_test']))
    for root, dirs, files in os.walk(folder_path):
        if pose_name in dirs:
            subfolder_path = os.path.join(root, pose_name)
            for name in os.listdir(subfolder_path):
                if file_name == name:
                    img_path = os.path.join(subfolder_path, name)
                    img = cv2.imread(img_path)
                    
                    results = pose.process(img)
                    mp_drawing.draw_landmarks(img, results.pose_landmarks, mp_pose.POSE_CONNECTIONS)
                    
                    plt.axis('off')
                    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
                    plt.title(f"File name: {file_name}\nTrue label: {pose_name}\nPredicted label: {y_to_pose(row['y_pred'])}")
                    plt.show()


Output hidden; open in https://colab.research.google.com to view.